### ISSUE TITLE
Releases page link

### ISSUE THREAD

**Issue by milannedic** [Digilent/Zybo-Z7-10-DMA#1]
Hello,

There is extra "s" in the link below so its broken this way. 
https://github.com/Digilent/Zybo-Z7-10-DMA/releasess

Check this line: "Download the most recent release ZIP archive ("Zybo-Z7-10-DMA-2018.2-*.zip") from the repo's releases page."

**Comment by artvvb** [comment]
Thanks for pointing this out!
